steps:
  # Install dependencies
  - name: 'python:3.9'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '-t', '.']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 'xml-convertion@appspot.gserviceaccount.com' 