steps:
  # Install dependencies
  - name: 'python:3.9'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '-t', '.']

  # Deploy to App Engine (as new version without shifting traffic)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--no-promote', '--version=v20241118', '--quiet']

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: '690574391086@cloudbuild.gserviceaccount.com'